# Copyright 2025 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "ngr-login-register-frontend"
play.http.router = prod.Routes
application.logger.name = ${appName}

play.filters.enabled += play.filters.csp.CSPFilter

# Default http client
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.play.bootstrap.AuthModule"

# Centralised Authorisation Module
play.modules.enabled += "centralisedauthorisation.resourceclient.modules.FrontendCentralisedAuthorisationModule"

# Centralised Authorisation Filter
play.filters.enabled += centralisedauthorisation.resourceclient.filters.ResourceClientFilter

# Custom error handler
play.http.errorHandler = "uk.gov.hmrc.ngrloginregisterfrontend.config.ErrorHandler"

# Play Modules
play.modules.enabled += "uk.gov.hmrc.ngrloginregisterfrontend.config.Module"
play.modules.enabled += "uk.gov.hmrc.mongo.play.PlayMongoModule"

microservice {
  services {
    auth {
        host = localhost
        port = 8500
    }
    contact-frontend {
        protocol = http
        host = localhost
        port = 9250
    }
    centralised-authorisation-server {
        host = localhost
        port = 15000
    }
    resource-client-store {
        host = localhost
        port = 15011
    }
    citizen-details {
          host = localhost
          port = 9337
    }
    ngr-dashboard-frontend {
        protocol = http
        host = localhost
        port = 1503
    }
    next-generation-rates {
        host = localhost
        port = 1500
    }
    address-lookup {
        host = localhost
        port = 9022
    }
    ngr-notify {
      host = "localhost"
      port = 1515
    }
    feedback-survey-frontend {
      host = "http://localhost:9514"
    }
    bas-gateway-frontend {
      host = "http://localhost:9553"
    }
    feedback-survey-frontend {
       host = "http://localhost:9514"
    }
  }
}

environment.host = "http://localhost:1502"

play.i18n.langCookieHttpOnly: "true"

contact-frontend.serviceId = "NGR"

time-to-live.time = "3"

mongodb {
  uri = "mongodb://localhost:27017/ngr-login-register-frontend"
}

auditing {
  enabled = false
}


# Change this value to true to enable Welsh translations to be loaded from messages.cy, and to display the language toggle
features.welsh-language-support = false
features.bridgeEnabled = false
addressLookupFrontendTest.enabled = true

# Replace play.i18n.langs with the commented out line below when your service has been fully translated into Welsh
# to enable Welsh translations for all content, including the standard headers and footers.
# play.i18n.langs = ["en", "cy"]
play.i18n.langs = ["en"]

# To integrate with tracking-consent-frontend, uncomment and update the
# gtm.container property below to be one of a, b, c, d, e, f or sdes
tracking-consent-frontend {
  gtm.container = "a"
}

timeout-dialog {
   timeout   = 900
   countdown = 120
}


public-access-allowed = false

allowedUsers {
    emailIds = ["user@test.com", "66666666email@email.com", "user3@example.com"]
}

play-frontend-hmrc.forceServiceNavigation = true
